[package]
name = "fit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
csv = "1.3.1"
nalgebra = "0.33.2"
plotters = "0.3.7"
serde = { version = "1.0.216", features = ["derive"] }
varpro = "0.10.1"
